name: kingfisher
description: A routing plugin for flutter
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
#  flutter:
#    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  test: ^1.17.3

flutter: