name: kingfisher
description: A routing plugin for dart
version: 1.0.0
author: Molkars
homepage: https://github.com/Molkars/kingfisher

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.17.4

flutter: